recipeInv:
  name: "{#orange}Create Custom Recipe"
  filler:
    material: BLACK_STAINED_GLASS_PANE
    name: "&r"
  shaped:
    material: hdb:3287
    name: "&3Shaped"
  shapeless:
    material: hdb:1988
    name: "&3Shapeless"
  confirm:
    material: LIME_STAINED_GLASS_PANE
    name: "{#green}Confirm"
choiceInv:
  name: "{#green}Add Items to Choice"
  filler:
    material: BLACK_STAINED_GLASS_PANE
    name: "&r"
  exact:
    material: TRIPWIRE_HOOK
    name: "{#green}Exact Match"
    enchanted: true
  material:
    material: TRIPWIRE_HOOK
    name: "{#yellow}Material Match"
  confirm:
    material: LIME_STAINED_GLASS_PANE
    name: "{#green}Confirm"